### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by rodrmartinez** [Zimbra-Community/zimbra-rocket#1]
Hi,
      I tried to use this simplet with Logon-only integration, the zimplet is shown in Zimbra but i get "The request did not succeed successfully.".

**Comment by ghost** [comment]
It's probably because the Zimlet expects the account in Rocket to be present.

Aka, if your zimbra account is user@example.com a rocket user user.example.com should exist.

**Comment by ghost** [comment]
updated the readme on that one

**Comment by rodrmartinez** [comment]
The user exists in Rocketchat, i can login disabling Iframe in RocketChat accounts, seems that the signOn action is not working

**Comment by ghost** [comment]
Did you configure the admin credentials?

**Comment by ghost** [comment]
Perhaps the ssl cert is not trusted.

I can debug for you, but I would need test accounts and ssh access to do it.

**Comment by rodrmartinez** [comment]
> Did you configure the admin credentials?
> […](#)
> On 14 Sep 2018, at 21:05, Rodrigo Martinez ***@***.***> wrote: The user exists in Rocketchat, i can login disabling Iframe in RocketChat accounts, seems that the signOn action is not working — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Yes, with the config.properties file. Sorry , I can't give you ssh access. Thanks

**Comment by ghost** [comment]
Ok the error is generic, to find out where it came from

Open the developer console in google chrome, check the network tab.

Maybe you can filter by ‘rocket’ and see which request fails

**Comment by ghost** [comment]
I will create a debug jar next week that spews out logging to see whats the matter

**Comment by rodrmartinez** [comment]
I checked with chrome, both requests failed ( redirect and signOn ) with the same response "The request did not succeed successfully."

**Comment by ghost** [comment]
@Izeka please download:
https://github.com/Zimbra-Community/zimbra-rocket/blob/master/extension/out/artifacts/extension_jar/extension.jar

Put it in /opt/zimbra/lib/ext/rocket/extension.jar 

Then `zmmailboxdctl restart`

And tail -f /opt/zimbra/log/zmmailboxd.out

And try again... what does it say?

**Comment by ghost** [comment]
Logging has been added to the jar above

**Comment by rodrmartinez** [comment]
Great, this is the logging output, thanks in advance

https://pastebin.com/UNebj2hZ

**Comment by ghost** [comment]
Unfortunately there is nothing in there that helps.

Can you do `cat /opt/zimbra/log/* | grep -C 25 -i rocket`, you can pm me the link to info@barrydegraaff.tk

**Comment by ghost** [comment]
is this a multi-server set-up?

**Comment by rodrmartinez** [comment]
The rocketchat server is running in a container behind nginx (proxy) that has a valid cert. Zimbra is not running in the same server.

> is this a multi-server set-up?

**Comment by ghost** [comment]
Nah, just seeing if you had a zimbra-multi-server. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by rodrmartinez** [comment]
Ah no, zimbra is not running in multi-server.

**Comment by rodrmartinez** [comment]
Finally I found the problem, it was a missconfiguration of  ssl certs in nginx, thank you for your time.
