### ISSUE TITLE
Question: Is their a way to login the user as just username?

### ISSUE THREAD

**Issue by rpelletierrefocus** [Zimbra-Community/zimbra-rocket#10]
For example, I would rather login/create the user as just jsmith instead of jsmith.domain.com.

Where would I need to make this change?  Thank you.

**Comment by rpelletierrefocus** [comment]
Closing, found how to do this myself, but need help to compile.

changed line 228 in Rocket.java to
```
if (this.createUser(zimbraAccount.getName(), zimbraAccount.getGivenName() + " " + zimbraAccount.getSn(), password, zimbraAccount.getName().substring(0, zimbraAccount.getName().indexOf("@")), zimbraAccount)) {
```

**Comment by ghost** [comment]
I have now added build.xml and makefile for use with ant and gnu make.

Just git clone the project, cd into the extension folder and run `make` or `ant jar`. You must have ant installed for it to build.
