### ISSUE TITLE
Zimbra-Rocket Chat

### ISSUE THREAD

**Issue by marabqa** [Zimbra-Community/zimbra-rocket#13]
This is regarding the new ZImbra 9 with rocket chat, the rocket chat is not working with new Zimbra 9 Modern UI, it works only with classic ui, is there a way to enable it in modern UI

**Comment by ghost** [comment]
no, not at this time

**Comment by marabqa** [comment]
If not at this time why you mentioned this will be worked with Zimbra 9

**Comment by ghost** [comment]
Hello,

At this time I do not have the time to create this integration but if you really need it, it can be implemented very easy using this: https://github.com/Zimbra/zm-zimlet-guide

Just put the rocketurl here: https://github.com/Zimbra/zm-zimlet-guide/blob/master/template/src/components/app/index.js#L12
