### ISSUE TITLE
Same login loop issue as  jorgedlcruz version

### ISSUE THREAD

**Issue by starxpert** [Zimbra-Community/zimbra-rocket#14]
Hello Barry,

We seem to have hit the same issue as:
https://github.com/jorgedlcruz/zimbra-rocket/issues/4

Namely, i have a loop with the login URL and never actually access Rocket chat

It is Zimbra 8.8.15 and latest Rocket chat

As there is no answer in the jorgedlcruz thread, i turn to you

Thank you in advance for the great work and time

Sincerely,

**Comment by ghost** [comment]
Make sure to configure X-Frame-Options/Access-Control-Allow-Origin on the Rocket Chat server side. You must remove these headers in a reverse proxy and re-add the correct ones for the integration to work. See the proxy-config folder for a basic example nginx/apache config.

**Comment by ghost** [comment]
During 2020 Google and various vendors have been pushing the requirement to set cookies with the SameSite and Secure attributes.

These attributes tell the browser if a cookie can be used when using multiple domains (3rd party cookie) and if a cookie may be used over an un-encrypted connection (http).

https://www.chromium.org/updates/same-site
https://digiday.com/media/what-is-chrome-samesite/#:~:text=Right%20now%2C%20the%20Chrome%20SameSite,%E2%80%94%20a%20first%2Dparty%20cookie.


Unfortunately some applications (RocketChat) set cookies on the client via Javascript, and do not support configuring the SameSite attribute, which is needed for it to run on a different domain than Zimbra.

This means that Rocket Chat needs to be installed on a subdomain similar to Zimbra. Aka zimbramail.example.com and rocketchat.example.com will work, zimbramail.example.io and rocketchat.example.com will not work.

https://security.stackexchange.com/questions/223473/for-samesite-cookie-with-subdomains-what-are-considered-the-same-site
