### ISSUE TITLE
Different login method to login using rocketchat mobile apps

### ISSUE THREAD

**Issue by WibyHere** [Zimbra-Community/zimbra-rocket#16]
Hi Team,

I found issue when login using rocketchat mobile apps (android).
After succesfully login to sso login page, I'm still on the sso page with the rocketchat menu display and haven't fully used the display from the mobile application.

![WhatsApp Image 2021-06-24 at 13 47 29](https://user-images.githubusercontent.com/1933801/123215616-dffce880-d4f2-11eb-9994-08773cabc6b3.jpeg)
![WhatsApp Image 2021-06-24 at 13 47 29 (2)](https://user-images.githubusercontent.com/1933801/123215649-e9865080-d4f2-11eb-80d0-248523d16171.jpeg)
![WhatsApp Image 2021-06-24 at 13 47 29 (3)](https://user-images.githubusercontent.com/1933801/123215682-f3a84f00-d4f2-11eb-8b98-a5d7cc13af31.jpeg)

Please help me to fix this issue

Regards,
Dwi

**Comment by ghost** [comment]
This should have been fixed, make sure you have:
https://github.com/Zimbra-Community/zimbra-rocket#choose-your-domain-wisely
