### ISSUE TITLE
No Login Form in Mobile device after update rocketchat to version 5.4.1

### ISSUE THREAD

**Issue by WibyHere** [Zimbra-Community/zimbra-rocket#18]
Hi,

Previously i using rocketchat 4.3.1 with zimbra and it worked on zimbra and mobile device.
But after upgrade to latest version rocketchat 5.4.1, i can't login in mobile device anymore (in zimbra still work).

can you help me to fix this issue?

After upgrade:
![WhatsApp Image 2022-12-20 at 2 25 21 PM](https://user-images.githubusercontent.com/1933801/208669701-950d3dca-8364-4ff5-9332-492dc5494b1b.jpeg)
![image](https://user-images.githubusercontent.com/1933801/208670124-c56410a3-c6bc-4a10-939d-d848caec688f.png)

Before upgrade:
![WhatsApp Image 2022-12-20 at 2 37 31 PM](https://user-images.githubusercontent.com/1933801/208669769-41b3b575-6450-4794-ae92-815a75cf2683.jpeg)

Thanks,
Regards,
Dwi

**Comment by xnextx** [comment]
I was using 4.x before and after upgrading to 5.x the iframe login stopped working.

**Comment by ghost** [comment]
Yes, version 5 broke this integration
