### ISSUE TITLE
iframe login blocks app login

### ISSUE THREAD

**Issue by vbartels** [Zimbra-Community/zimbra-rocket#4]
With a working installation of the zimlet I am no longer able to use the apps on windows and mac OS. They Loop a "Log In" Page and block connection to Zimbra.
Native Apps wich use the API instead of wrapping the web version like iOS do work. Login via RocketChat Tab inside zimbra works, also.

**Comment by ghost** [comment]
yeah, I do not think that works, try iframe only integration

**Comment by vbartels** [comment]
...how? Whats the difference?

**Comment by ghost** [comment]
[ https://github.com/Zimbra-Community/zimbra-rocket#this-zimlet-supports-optional-auto-login-to-rocket-using-the-rocket-api | https://github.com/Zimbra-Community/zimbra-rocket#this-zimlet-supports-optional-auto-login-to-rocket-using-the-rocket-api ] 

Disable all the iframe login settings in the rocket UI and then remove the server extension from Zimbra and 
follow the steps under Basic integration

**Comment by vbartels** [comment]
Hm - okay thank you! Basic integration is not an option for us. However this solves the app login problem. :)

**Comment by ghost** [comment]
I just remembered that if you use the full integration, it means that Zimbra will create accounts on 
Rocket. 

And the first time the user will see a dialog telling them their account is created, also they will 
get a username and password that should allow you to log on using the app.
