### ISSUE TITLE
RockChat Blocked by Content Security Policy

### ISSUE THREAD

**Issue by tuxcrafter** [Zimbra-Community/zimbra-rocket#6]
Blocked by Content Security Policy

An error occurred during a connection to saml.example.org.

Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.

![Zimbra_Rocket Chat_-_2020-01-10_22 52 04](https://user-images.githubusercontent.com/9133399/72204759-a14cad00-347b-11ea-90c1-7a0fae163fdb.png)

security.mixed_content.block_active_content -> false did not work

I would really appreciate a header fix on the server side to make this work again.

**Comment by ghost** [comment]
The headers to set are documented in https://github.com/Zimbra-Community/zimbra-rocket/tree/master/proxy-config
